---
- name: Install phpIPAM
  hosts: all
  become: yes
  gather_facts: true
    
  tasks:
    - name: Install required packages
      package:
        name: 
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-intl
          - php-pear
          - php-imap
          - php-memcache
          - php-pspell
          - php-tidy
          - php-xmlrpc
          - php-mbstring
          - php-gmp
          - php-json
          - php-xml
          - php-fpm
          - git
          - mariadb-server
          - mariadb-client
          - apache2
          - libapache2-mod-php
          - php-curl
          - php-xmlrpc
          - php-intl
          - php-gd
        state: present
        update_cache: yes

    - name: Enable and start MariaDB service
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: Create phpIPAM database and user
      command: >
        mysql -u root -e "
        CREATE DATABASE phpipam;
        GRANT ALL ON phpipam.* TO phpipam@localhost IDENTIFIED BY '{{ morpheus['customOptions']['phpipammysqlpw'] }}';
        FLUSH PRIVILEGES;"

    - name: Clone phpIPAM repository for Dev
      command:
        cmd: git clone --recursive https://github.com/phpipam/phpipam.git /var/www/html/phpipam
      when: morpheus['customOptions']['lifecyclestage'] == "Dev"

    - name: Download tgz for phpIPAM  
      ansible.builtin.get_url:
        url: "{{ morpheus['customOptions']['prodversions'] }}"
        dest: "/tmp/phpipam.tgz"
      when: morpheus['customOptions']['lifecyclestage'] != "Dev"

    - name: Create the phpipam directory
      ansible.builtin.file:
        path: /var/www/html/phpipam
        state: directory
      when: morpheus['customOptions']['lifecyclestage'] != "Dev"

    - name: Extract phpIPAM
      ansible.builtin.unarchive:
        src: "/tmp/phpipam.tgz"
        dest: "/var/www/html/phpipam"
        extra_opts: [--strip-components=1]
        remote_src: yes
      when: morpheus['customOptions']['lifecyclestage'] != "Dev"

    - name: copy phpIPAM repository
      command:
        cp /var/www/html/phpipam/config.dist.php /var/www/html/phpipam/config.php

    - name: Replace line in file 
      replace:
        path: /var/www/html/phpipam/config.php
        regexp: "^\\$db\\['pass'\\] = 'phpipamadmin';"
        replace: "$db['pass'] = '{{ morpheus['customOptions']['phpipammysqlpw'] }}';"

    - name: Add allow_untested_php_versions config
      lineinfile:
        path: /var/www/html/phpipam/config.php  
        line: "$allow_untested_php_versions=true;"
        state: present

    - name: disable default virtual host  
      command:
        a2dissite 000-default.conf

    - name: rewrite
      command:
        a2enmod rewrite

    - name: ssl
      command:
        a2enmod ssl

    - openssl_privatekey:
        path: /etc/ssl/phpipam.key
        size: 2048 

    - openssl_csr:
        path: /etc/ssl/phpipam.csr
        privatekey_path: /etc/ssl/phpipam.key

    - openssl_certificate:
        provider: selfsigned
        path: /etc/ssl/phpipam.crt
        privatekey_path: /etc/ssl/phpipam.key
        csr_path: /etc/ssl/phpipam.csr

    - name: Enable phpIPAM site
      command: a2ensite phpipam
      args:
        warn: no  

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: sql schema
      ansible.builtin.shell: mysql -u phpipam -p{{ morpheus['customOptions']['phpipammysqlpw'] }} phpipam < /var/www/html/phpipam/db/SCHEMA.sql
